### ISSUE TITLE
$CisionItem isnt available in template

### ISSUE THREAD

**Issue by chrillep** [Cyclonecode/cision-block#4]
```php
global $CisionItem;
```
needs to be added to the post template otherwise it's not avaiable
https://github.com/Cyclonecode/cision-block/blob/45d1da812b86565b4d2bea85bda0643daaba5bb2/src/Frontend/templates/cision-block-post.php#L12-L15

<img width="1214" alt="Skärmavbild 2022-01-26 kl  08 28 27" src="https://user-images.githubusercontent.com/1267931/151120958-edc7e930-5e6e-4fb8-bcc5-064ec609e3f5.png">
3

**Comment by Cyclonecode** [comment]
This is fixed in 2.7.0

**Comment by chrillep** [comment]
ok testar.

**Comment by chrillep** [comment]
funkar perfa! tack!
